### ISSUE TITLE
Domo Compiler tripped up by Ecto.Schema.Metadata type

### ISSUE THREAD

**Issue by capitalist** [IvanRublev/Domo#5]
### Environment

* Elixir version (elixir -v): Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit] Elixir 1.12.2 (compiled with Erlang/OTP 24)
* Domo version (mix deps | grep domo | head -1):   locked at 1.3.3 (domo) 10374b4a
* TypedStruct version (mix deps | grep typed_struct | head -1): not present

### Actual behavior

```
** (MatchError) no match of right hand side value: {:"::", [], [{:t, [], []}, {:t, [line: 50], [{:module, [line: 50], []}]}]}
   (domo 1.3.3) lib/domo/type_ensurer_factory.ex:37: Domo.TypeEnsurerFactory.collect_types_for_domo_compiler/3
    (elixir 1.12.2) lib/enum.ex:930: Enum."-each/2-lists^foreach/1-0-"/2
    (domo 1.3.3) lib/mix/tasks.compile.domo_compiler.ex:73: Mix.Tasks.Compile.DomoCompiler.build_ensurer_modules/2
    (domo 1.3.3) lib/mix/tasks.compile.domo_compiler.ex:57: Mix.Tasks.Compile.DomoCompiler.run/1
    (mix 1.12.2) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.12.2) lib/mix/tasks/compile.all.ex:92: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.12.2) lib/mix/tasks/compile.all.ex:72: Mix.Tasks.Compile.All.compile/4
    (mix 1.12.2) lib/mix/tasks/compile.all.ex:59: Mix.Tasks.Compile.All.with_logger_app/2
```

### Expected behavior

Compiles

**Comment by capitalist** [comment]
Seems to be this line in ecto causing the MatchError: https://github.com/elixir-ecto/ecto/blob/v3.7.1/lib/ecto/schema/metadata.ex#L50

**Comment by IvanRublev** [comment]
It turns out that Domo is compatible with Ecto of versions <= 3.6.2 and fails to import Schema type with Ecto releases 3.7.x. 
Let's see what can be done to level up the compatibility.

**Comment by IvanRublev** [comment]
Hey,

I'm delighted to hear that Domo spotlighted potential bug sources for you!

Domo doesn't support self-referenced types. So no trees validation is possible yet 😄

The `Ecto.Metadata` issue is fixed with [version 1.3.4](https://hex.pm/packages/domo/1.3.4), please, give it a try
