### ISSUE TITLE
Support for `@opaque` types in `precond`

### ISSUE THREAD

**Issue by BasileNouvellet** [IvanRublev/Domo#6]
Hey, thanks for this great library!

Is support for `@opaque` types in `precond` macro on the roadmap by any chance?

Example:

```elixir
defmodule User do
  use Domo

  # No errors when using usual @type
  # @type id :: String.t()
  # Error when using @opaque type
  @opaque id :: String.t()
  precond id: &validate_id/1

  @type t :: %__MODULE__{id: id()}

  @enforce_keys [:id]
  defstruct [:id]

  defp validate_id(""), do: {:error, "can't be empty"}
  defp validate_id(_id), do: :ok
end
```

This throws the following compilation error:

```
** (FunctionClauseError) no function clause matching in anonymous fn/1 in Domo._plan_precond_checks/2    
    
    The following arguments were given to anonymous fn/1 in Domo._plan_precond_checks/2:
    
        # 1
        {:opaque, {:id, {:remote_type, 8, [{:atom, 0, String}, {:atom, 0, :t}, []]}, []}}
    
    (domo 1.2.9) lib/domo.ex:562: anonymous fn/1 in Domo._plan_precond_checks/2
    (elixir 1.12.3) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
    (domo 1.2.9) lib/domo.ex:562: Domo._plan_precond_checks/2
    (stdlib 3.16) lists.erl:1267: :lists.foldl/3
    (stdlib 3.16) erl_eval.erl:685: :erl_eval.do_apply/6
```

If I remove the `precond` line, I have no errors, even with the `@opaque` type.

**Comment by IvanRublev** [comment]
Hey, thanks for finding a bug. Let's see what can be done to hotfix this.

**Comment by IvanRublev** [comment]
`@opaque` types and attached preconditions are supported in [version 1.4.0](https://hex.pm/packages/domo/1.4.0).

**Comment by BasileNouvellet** [comment]
Works like a charm, thank you!
